import Head from 'next/head';
import { Inter } from '@next/font/google';
import { BsFillMoonStarsFill, BsLaptopFill } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillInstagram  } from "react-icons/ai";
import Image from "next/image";
import andre from "../public/andre_img.JPG";
import design from "../public/design.png";
import code from "../public/code.png";
// import CV from "../public/Andre_resume.pdf";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const [ darkMode, setDarkMode ] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      {/* FILE PROPERTIES  */}
      <Head>
        <title>Andre Ene's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
     
      {/* PAGE CONTENT  */}
      <main className=" bg-white dark:bg-slate-800">
        {/* navbar  */}

          <nav className='py-5 px-10 mb-12 flex justify-between fixed top-0 w-[100%] bg-white dark:bg-slate-800 shadow-lg z-30'>
            <h1 className='text-xl font-burtons'>Dev.Andre</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)}/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='https://drive.google.com/file/d/1tepTzVkKRp4ohHdL-8GIrviRFBhsTzyH/view?usp=sharing' download>Resume</a>
              </li>
            </ul>
          </nav>

      {/* body  */}
          <div className='pt-[100px] px-10 md:px-10'>
        {/* introduction section  */}
            <section className='min-h-screen'>
              <div className='text-center p-10 '>
                <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ene-Inyang Andre</h2>
                <h3 className='text-2xl py-2 md:text-3xl font-bold text-gray-800 dark:text-gray-400'>Front End Web Developer.</h3>
                <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-300 md:text-xl max-w-2xl mx-auto'>
                Hello there, I am Ene-Inyang Andre, a Front End Web Developer based in Lagos, Nigeria.
                I love combining the worlds of logic and creative design to make eye-catching, accessible,
                and user-friendly websites and applications
                I am exicted to make the leap and continue refining my skills with the right company.
                </p>
              </div>
              <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
                 <a href="https://www.linkedin.com/in/andreene/" target="_blank"> <AiFillLinkedin className='cursor-pointer dark:text-gray-400' /></a>
                 <a href="https://devandre-portfolio.netlify.app/" target="_blank"> <BsLaptopFill className='cursor-pointer dark:text-gray-400' /></a>
                
                  <a href="https://github.com/dev-eneandre" target="_blank"><AiFillGithub className='cursor-pointer dark:text-gray-400' /></a>              
              </div>
              <div className='relative mx-auto mb-10 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
                <Image className="object-cover" src={andre} fill />
              </div>
            </section>

        {/*  Services Offered Section  */}
        <section>
            <div>
              <h3 className='text-4xl py-2  text-center font-bold'>Services I Offer</h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-300 md:text-xl max-w-2xl mx-auto">
                  Since the beginning of my journey as a freelance designer and
                  developer, I've done remote work for
                  <span className="text-teal-500 cursor-pointer"> agencies </span>
                  consulted for <span className="text-teal-500 cursor-pointer">startups </span>
                  and collaborated with talanted people to create digital products
                  for both business and consumer use.
                  I work the client-side of a web application, convert the design into a real-life application using
                  <span className="text-teal-500 cursor-pointer font-semibold"> React Js, HTML, CSS
                   and JavaScript</span>  and also ensure responsive and adaptive User Interface.
                </p>          
            </div>

          {/* CARDS   */}
            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10   '>
                <Image className="mx-auto" src={design} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>Beautiful Designs.</h3>
                <p className='dark:text-gray-500'> 
                  Creating elegant designs suited for your needs following core design theory.
                </p>
                <h4 className='py-4 text-teal-600 font-medium'>Design Tools I Use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-500 '>React JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500 '>Redux</p>
                <p className='text-gray-800 py-1 dark:text-gray-500 '>Next JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500 '>TailWind CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500 '>Bootstrap</p>
              </div>
            
              <div className='text-center shadow-lg p-10 rounded-xl my-10   '>
                <Image className="mx-auto" src={consulting} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>Beautiful  Designs.</h3>
                <p className='dark:text-gray-500'>
                  Creating elegant designs suited for your needs following core design theory.
                </p>
                <h4 className='py-4 text-teal-600 font-medium'>Design Tools I Use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-500'>React JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Redux</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Next JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>TailWind CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Bootstrap</p>
              </div>
            
              
              <div className='text-center shadow-lg p-10 rounded-xl my-10   '>
                <Image className="mx-auto" src={code} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>Beautiful Designs.</h3>
                <p className='dark:text-gray-500'>
                    Creating elegant designs suited for your needs following core design theory.
                </p>
                <h4 className='py-4 text-teal-600 font-medium'>Design Tools I Use</h4>
                <p className='text-gray-800 py-1 dark:text-gray-500'>React JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Redux</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Next JS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>TailWind CSS</p>
                <p className='text-gray-800 py-1 dark:text-gray-500'>Bootstrap</p>
              </div>
            </div>
          </section>

          {/* projects section  */}
          <section>
            
          <div>
              <h3 className='text-4xl py-2  text-center font-bold'>DISCLAIMER!!!</h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-300 md:text-xl max-w-xl mx-auto">

              This is a sample project on tailwind CSS and Next JS. You can take a look at my projects here on 
              <span className='text-teal-500 cursor-pointer'><a href='https://devandre-portfolio.netlify.app/' target='_blank'> my portfolio </a></span>
              or contact me via <span className='text-teal-500 cursor-pointer'> +2349058286910</span> or email me at <span className='text-teal-500 cursor-pointer'>iameneandre@gmail.com</span>. 
              You can also download my resume above.
              </p>
                        
            </div>



            <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap '>
              <div className='basis-1/3 flex-1' ><Image src={web1} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
              <div className='basis-1/3 flex-1'><Image src={web2} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
              <div className='basis-1/3 flex-1'><Image src={web3} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
              <div className='basis-1/3 flex-1'><Image src={web4} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
              <div className='basis-1/3 flex-1'><Image src={web5} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
              <div className='basis-1/3 flex-1'><Image src={web6} className='rounded-lg object-cover ' width={'100%'} height={'100%'} layout="responsive" /></div>
            </div>
          </section>

          </div>
      </main>
    </div>
  )
}
